name: artscope
favicon: null
layout_spectrum: 0.39826
typography_spectrum: 0.15231
title: Fine Art Prints
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5e5e5e'
    - '#1a181b'
    - '#178b95'
    - '#37b9db'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
